import express from "express";
import { genAI } from "../index.js";
const router = express.Router();

router.post("/", async (req, res) => {
  try {
    const { url } = req.body;


    const articleContent = await fetchArticleContent(url);

    if (!articleContent) {
      return res.status(400).json({ error: "Could not fetch article content" });
    }

    const summary = await generateSummaryWithGemini(articleContent);

    res.json({
      summary: summary,
      source: "Generated by Ai",
    });
  } catch (err) {
    console.error("Error in summarize-link:", err);
    res.status(500).json({ error: err.message });
  }
});

async function fetchArticleContent(url) {
  try {
    const response = await fetch(url);
    const html = await response.text();

    const text = html
      .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, "")
      .replace(/<style\b[^<]*(?:(?!<\/style>)<[^<]*)*<\/style>/gi, "")
      .replace(/<[^>]+>/g, " ")
      .replace(/\s+/g, " ")
      .trim()
      .substring(0, 5000);

    return text;
  } catch (error) {
    console.error("Error fetching article content:", error);
    return null;
  }
}

async function generateSummaryWithGemini(content) {
  try {
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash-lite" });
    const prompt = `
    Please analyze the following article content.
    
    First, provide a concise summary that is 2-4 sentences long.
    
    After the summary, add a section titled "Key Points:" and list the most important 3-4 takeaways in a bullet point format (using * or -).

    Article Content:
    ${content}
  `;
    const { response } = await model.generateContent(prompt);
    return response.text();
  } catch (error) {
    console.error("Error generating summary with Gemini:", error);
    throw new Error("Failed to generate summary");
  }
}

export default router;
